FROM golang:1.21.6-alpine as builder

RUN apk update && apk add git make

RUN go install golang.org/x/tools/cmd/goimports@latest
RUN go install -v github.com/rogpeppe/godef@v1.1.2

WORKDIR /app

COPY . .

COPY go.* ./

RUN go mod download

RUN go mod verify

# CMD ["go", "run", "./cmd/"]
