services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_dev
    tty: true
    volumes:
      - .:/app
    restart: always
    ports:
      - 6000:80

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5434:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
