name: deploy

on: workflow_dispatch

env:
  AWS_REGION: ap-northeast-1
  REPOSITORY_NAME: currency-converter

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: login to ECR
        run: aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com
      - name: build image
        run: docker build -t ${{ env.REPOSITORY_NAME }} .
      - name: tag image
        run: docker tag ${{ env.REPOSITORY_NAME }}:latest ${{ secrets.AWS_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/${{ env.REPOSITORY_NAME }}:latest
      - name: push image to ecr
        run: docker push ${{ secrets.AWS_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/${{ env.REPOSITORY_NAME }}:latest
